version: '2'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:v1.7.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules:/etc/prometheus/alert.rules
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

  node-exporter:
    image: prom/node-exporter:v0.14.0
    ports:
      - '9100:9100'

  skytap-exporter:
    restart: always
    build: ./skytap-exporter
    environment:
      - PYTHONUNBUFFERED=true
    ports:
      - '9118:9118'
    command: >
      python skytap_exporter.py
        --endpoint=http://10.42.100.179:5050/api/skytap/usage
        --port=9118
        --interval=1800

  grafana:
    image: grafana/grafana:4.4.2
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
